export const fourPoledComponentSet: Set<string> = new Set([
  "antenna",
  "backup_supply",
  "beacon",
  "cable",
  "equipment_shelter",
  "fuel_tank",
  "ladder",
  "lightning_rod",
  "microwave",
  "power_cabinate",
  "rrh",
  "tma",
  "waveguides",
]);

export const monopoleComponentSet: Set<string> = new Set([
  "antenna",
  "antenna_mounting_frames",
  "backup_supply",
  "beacon",
  "cable",
  "down_conductor",
  "equipment_shelter",
  "fuel_tank",
  "lightning_rod",
  "microwave",
  "monopole",
  "power_cabinate",
  "rf_jumpers",
  "rru",
]);
export const tripoleComponentSet: Set<string> = new Set([
  "antenna",
  "backup_supply",
  "beacon",
  "cable",
  "equipment_shelter",
  "fuel_tank",
  "ladder",
  "lightning_rod",
  "microwave",
  "power_cabinate",
  "waveguides",
]);
